# HTTP — перенаправление на HTTPS
server {
    listen 80;
    server_name kornevgmbh.com www.kornevgmbh.com;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}


# HTTPS — основная конфигурация
server {
    listen 443 ssl;
    http2 on;
    server_name kornevgmbh.com www.kornevgmbh.com;
    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/kornevgmbh.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kornevgmbh.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Ваши локации (пример)
    location / {
        proxy_pass http://frontend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api {
        proxy_pass http://backend:5000;
        proxy_set_header Host $host;
    }

    location /cloudbeaver/ {
        proxy_pass http://cloudbeaver:8978/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    # добавьте другие локации по необходимости
}